 
MAT 1011 
MATLAB
L31+L32
FALL SEMESTER 2019-20
SHARADINDU ADHIKARI
19BCE2105
Question 1
Find the area of the region bounded by the curve 𝑦 = 𝑥
2 − 2𝑥 and the line 𝑦 = 𝑥.
clear all;
clc;
syms x;
f=input('Enter the upper curve f(x): ');
g=input('Enter the lower curve g(x): ');
L=input('Enter the limits of integration for x [a,b]:');
a=L(1); b=L(2);
Area=int(f-g,x,a,b);
disp(['Area bounded by the curves f(x) and g(x) is: ',char(Area)]);
x1=linspace(a,b,20);y1=subs(f,x,x1);
x2=x1;y2=subs(g,x,x1);
plot(x1,y1);hold on; plot(x2,y2);hold off;
xlabel('x-axis');ylabel('y-axis');
legend('f(x)','g(x)');
grid on;
Enter the upper curve f(x): x
Enter the lower curve g(x): (x^2)-(2*x)
Enter the limits of integration for x [a,b]:[0,3]
Area bounded by the curves f(x) and g(x) is: 9/2
Question 2
Find the volume of the solid generated by revolving about the x-axis the region bounded 
by the curve 𝑦 =
4
𝑥
2+4
, the x-axis, and the lines 𝑥 = 0 and 𝑥 = 2.
clear all;
clc;
syms x
f=input('Enter the function f(x) to be rotated about x axis: ');
a=input('Enter the line 1, x= ');
b=input('Enter the line 2, x= ');
vol=pi*int(f^2,a,b);
disp(['Volume of solid of revolution is: ',char(vol)]);
x1=linspace(a,b,20); y1=subs(f,x,x1);
x2=x1; y2=ones(length(x1));
plot(x1,y1);hold on;
plot(x2,y2);hold off;
xlabel('x-axis');ylabel('y-axis')
legend('The curve y=f(x)','The axis of revolution x');
title('Volume of solid generated by revolving about the x axis');
grid on;
Enter the function f(x) to be rotated about x axis: 4/((x^2)+4)
Enter the line 1, x= 0
Enter the line 2, x= 2
Volume of solid of revolution is: pi*(pi/4 + 1/2)
Question 3
Find the Laplace transform of the function 𝑓(𝑡) = 𝑠𝑖𝑛2𝑡 𝑠𝑖𝑛3𝑡.
clear all
clc
syms t;
f=input('Enter the function of t: ');
F=laplace(f);
disp(['L{',char(f),'}=',char(F)]);
Enter the function of t: sin(2*t)*sin(3*t)
L{sin(2*t)*sin(3*t)}=s/(2*(s^2 + 1)) - s/(2*(s^2 + 25))
Question 4
Find the inverse Laplace transform of the function 𝐹(𝑠) = 
𝑠
2+2𝑠−4
(𝑠
2+2𝑠+5)(𝑠
2+2𝑠+2)
clear all;
clc;
syms s;
F=input('Enter the function of s: ');
f=ilaplace(F);
disp(['f(t)=',char(f)]);
Enter the function of s: ((s^2)+(2*s)-4)/(((s^2)+(2*s)+5)*((s^2)+(2*s)+2))
f(t)=(3*sin(2*t)*exp(-t))/2 - 2*exp(-t)*sin(t)
End 